---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-kustomize
  namespace: tekton-builds
spec:
  params:
  - name: container_image
    type: string
  - name: container_tag
    type: string
  - name: manifests_path
    type: string
  workspaces:
  - name: source
  steps:
  - name: version
    image: nekottyo/kustomize-kubeval
    script: |
      cd $(workspaces.source.path)/$(params.manifests_path)
      kustomize edit set image $(params.container_image)=$(params.container_image):$(params.container_tag)
      kustomize build | kubectl apply --filename -
