apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-git-clone
  namespace: tekton-builds
spec:
  workspaces:
  - name: source
  params:
  - name: url
    type: string
  steps:
  - name: clone
    image: bitnami/git
    script: |
      cd $(workspaces.source.path)
      echo $(workspaces.source.path)
      git clone https://$(params.url)
      cat $(workspaces.source.path)/shark-app/Dockerfile
