apiVersion: argoproj.io/v1aplhav1
kind: Rollout
metadata:
   name: shark-app-deployment
spec:
   template:
      metadata:
        labels:
          name: shark-app
          type: fe
      spec:
         containers:
           - name: shark-app
             image: shaktiug/node-shark-app:v1.1
             ports:
               - containerPort: 8080
                 protocol: TCP
   replicas: 2
   selector:
      matchLabels:
         type: fe
   strategy:
           blueGreen:
                   activeService: shark-svc-active
                   previewService:  shark-svc-preview
                   autoPromotionEnabled: false
