apiVersion: v1
kind: Service
metadata:
    name: shark-preview-service
spec:
    type: NodePort
    ports:
       - targetPort: 8080
         port: 80
    selector:
       name: shark-app
       type: fe 
